<?xml version="1.0"?>
<!--
  Humanoid Robot Xacro File

  Xacro (XML Macro) provides:
  - Properties (variables) for reusable values
  - Macros for reusable structures
  - Math expressions
  - Include files for modularity

  Build URDF from Xacro:
  xacro humanoid.xacro > humanoid_generated.urdf
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="humanoid_xacro">

  <!-- ==================== PROPERTIES ==================== -->
  <!-- Physical properties - easy to tune in one place -->
  <xacro:property name="torso_mass" value="10.0"/>
  <xacro:property name="head_mass" value="1.0"/>
  <xacro:property name="upper_arm_mass" value="1.0"/>
  <xacro:property name="forearm_mass" value="0.8"/>
  <xacro:property name="hand_mass" value="0.3"/>
  <xacro:property name="thigh_mass" value="2.0"/>
  <xacro:property name="shin_mass" value="1.5"/>
  <xacro:property name="foot_mass" value="0.5"/>

  <!-- Dimensions -->
  <xacro:property name="torso_length" value="0.4"/>
  <xacro:property name="torso_width" value="0.3"/>
  <xacro:property name="torso_depth" value="0.2"/>
  <xacro:property name="head_radius" value="0.1"/>
  <xacro:property name="upper_arm_length" value="0.2"/>
  <xacro:property name="forearm_length" value="0.18"/>
  <xacro:property name="thigh_length" value="0.3"/>
  <xacro:property name="shin_length" value="0.28"/>

  <!-- Joint limits -->
  <xacro:property name="shoulder_limit" value="3.14"/>
  <xacro:property name="elbow_limit" value="2.5"/>
  <xacro:property name="hip_limit" value="1.57"/>
  <xacro:property name="knee_limit" value="2.5"/>
  <xacro:property name="ankle_limit" value="0.5"/>

  <!-- ==================== MATERIALS ==================== -->
  <material name="blue">
    <color rgba="0.2 0.4 0.8 1.0"/>
  </material>

  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>

  <material name="white">
    <color rgba="0.9 0.9 0.9 1.0"/>
  </material>

  <!-- ==================== MACROS ==================== -->

  <!-- Macro for calculating box inertia -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertial>
      <mass value="${m}"/>
      <inertia
        ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
        iyy="${m*(x*x+z*z)/12}" iyz="0"
        izz="${m*(x*x+y*y)/12}"/>
    </inertial>
  </xacro:macro>

  <!-- Macro for calculating cylinder inertia -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia
        ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
        iyy="${m*(3*r*r+h*h)/12}" iyz="0"
        izz="${m*r*r/2}"/>
    </inertial>
  </xacro:macro>

  <!-- Macro for sphere inertia -->
  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia
        ixx="${2*m*r*r/5}" ixy="0" ixz="0"
        iyy="${2*m*r*r/5}" iyz="0"
        izz="${2*m*r*r/5}"/>
    </inertial>
  </xacro:macro>

  <!-- Macro for creating an arm -->
  <xacro:macro name="arm" params="side reflect">
    <!-- Shoulder -->
    <link name="${side}_shoulder">
      <visual>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
      <xacro:sphere_inertia m="0.5" r="0.05"/>
    </link>

    <joint name="${side}_shoulder_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${side}_shoulder"/>
      <origin xyz="0 ${reflect*0.15} 0.15" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-shoulder_limit}" upper="${shoulder_limit}" effort="50" velocity="2.0"/>
    </joint>

    <!-- Upper Arm -->
    <link name="${side}_upper_arm">
      <visual>
        <geometry>
          <cylinder radius="0.03" length="${upper_arm_length}"/>
        </geometry>
        <origin xyz="0 ${reflect*upper_arm_length/2} 0" rpy="1.5708 0 0"/>
        <material name="blue"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.03" length="${upper_arm_length}"/>
        </geometry>
        <origin xyz="0 ${reflect*upper_arm_length/2} 0" rpy="1.5708 0 0"/>
      </collision>
      <xacro:cylinder_inertia m="${upper_arm_mass}" r="0.03" h="${upper_arm_length}"/>
    </link>

    <joint name="${side}_upper_arm_joint" type="fixed">
      <parent link="${side}_shoulder"/>
      <child link="${side}_upper_arm"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Forearm -->
    <link name="${side}_forearm">
      <visual>
        <geometry>
          <cylinder radius="0.025" length="${forearm_length}"/>
        </geometry>
        <origin xyz="0 ${reflect*forearm_length/2} 0" rpy="1.5708 0 0"/>
        <material name="gray"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.025" length="${forearm_length}"/>
        </geometry>
        <origin xyz="0 ${reflect*forearm_length/2} 0" rpy="1.5708 0 0"/>
      </collision>
      <xacro:cylinder_inertia m="${forearm_mass}" r="0.025" h="${forearm_length}"/>
    </link>

    <joint name="${side}_elbow_joint" type="revolute">
      <parent link="${side}_upper_arm"/>
      <child link="${side}_forearm"/>
      <origin xyz="0 ${reflect*upper_arm_length} 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="0" upper="${elbow_limit}" effort="30" velocity="2.0"/>
    </joint>

    <!-- Hand -->
    <link name="${side}_hand">
      <visual>
        <geometry>
          <box size="0.04 0.08 0.02"/>
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.04 0.08 0.02"/>
        </geometry>
      </collision>
      <xacro:box_inertia m="${hand_mass}" x="0.04" y="0.08" z="0.02"/>
    </link>

    <joint name="${side}_wrist_joint" type="revolute">
      <parent link="${side}_forearm"/>
      <child link="${side}_hand"/>
      <origin xyz="0 ${reflect*forearm_length} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.0" upper="1.0" effort="10" velocity="2.0"/>
    </joint>
  </xacro:macro>

  <!-- Macro for creating a leg -->
  <xacro:macro name="leg" params="side reflect">
    <!-- Hip -->
    <link name="${side}_hip">
      <visual>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
      <xacro:sphere_inertia m="0.5" r="0.05"/>
    </link>

    <joint name="${side}_hip_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${side}_hip"/>
      <origin xyz="0 ${reflect*0.1} -0.2" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-hip_limit}" upper="${hip_limit}" effort="100" velocity="2.0"/>
    </joint>

    <!-- Thigh -->
    <link name="${side}_thigh">
      <visual>
        <geometry>
          <cylinder radius="0.04" length="${thigh_length}"/>
        </geometry>
        <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
        <material name="blue"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.04" length="${thigh_length}"/>
        </geometry>
        <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
      </collision>
      <xacro:cylinder_inertia m="${thigh_mass}" r="0.04" h="${thigh_length}"/>
    </link>

    <joint name="${side}_thigh_joint" type="fixed">
      <parent link="${side}_hip"/>
      <child link="${side}_thigh"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Shin -->
    <link name="${side}_shin">
      <visual>
        <geometry>
          <cylinder radius="0.035" length="${shin_length}"/>
        </geometry>
        <origin xyz="0 0 ${-shin_length/2}" rpy="0 0 0"/>
        <material name="gray"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.035" length="${shin_length}"/>
        </geometry>
        <origin xyz="0 0 ${-shin_length/2}" rpy="0 0 0"/>
      </collision>
      <xacro:cylinder_inertia m="${shin_mass}" r="0.035" h="${shin_length}"/>
    </link>

    <joint name="${side}_knee_joint" type="revolute">
      <parent link="${side}_thigh"/>
      <child link="${side}_shin"/>
      <origin xyz="0 0 ${-thigh_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="0" upper="${knee_limit}" effort="80" velocity="2.0"/>
    </joint>

    <!-- Foot -->
    <link name="${side}_foot">
      <visual>
        <geometry>
          <box size="0.15 0.08 0.03"/>
        </geometry>
        <origin xyz="0.03 0 0" rpy="0 0 0"/>
        <material name="orange"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.15 0.08 0.03"/>
        </geometry>
        <origin xyz="0.03 0 0" rpy="0 0 0"/>
      </collision>
      <xacro:box_inertia m="${foot_mass}" x="0.15" y="0.08" z="0.03"/>
    </link>

    <joint name="${side}_ankle_joint" type="revolute">
      <parent link="${side}_shin"/>
      <child link="${side}_foot"/>
      <origin xyz="0 0 ${-shin_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-ankle_limit}" upper="${ankle_limit}" effort="50" velocity="2.0"/>
    </joint>
  </xacro:macro>

  <!-- ==================== ROBOT STRUCTURE ==================== -->

  <!-- Base/Torso -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${torso_width} ${torso_depth} ${torso_length}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${torso_width} ${torso_depth} ${torso_length}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${torso_mass}" x="${torso_width}" y="${torso_depth}" z="${torso_length}"/>
  </link>

  <!-- Head -->
  <link name="head">
    <visual>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="${head_mass}" r="${head_radius}"/>
  </link>

  <joint name="head_joint" type="revolute">
    <parent link="base_link"/>
    <child link="head"/>
    <origin xyz="0 0 ${torso_length/2 + head_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>

  <!-- Arms (using macro) -->
  <xacro:arm side="left" reflect="1"/>
  <xacro:arm side="right" reflect="-1"/>

  <!-- Legs (using macro) -->
  <xacro:leg side="left" reflect="1"/>
  <xacro:leg side="right" reflect="-1"/>

</robot>
